# .github/workflows/ekart-CICD.yml

name: Ekart CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ekart

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: flask
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root123
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t my-ekart-app .

      - name: Push Docker image to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag my-ekart-app:latest ajit0101/my-ekart-app:1.0
          docker push ajit0101/my-ekart-app:1.0
